print("What is your name?")
a = input()
print("How old are you?")
b = input()
print("Where are you live?")
c = input()
print("This is {0}.".format(a))
print("It is {0}.".format(b))
print("(S)he live in {0}.".format(c))
